# Generated by Django 4.1.7 on 2023-02-23 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('prompt_template', models.TextField()),
                ('temperature', models.FloatField(default=1.0)),
                ('max_tokens', models.IntegerField(default=1000)),
            ],
        ),
        migrations.CreateModel(
            name='AssistantInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('input_type', models.CharField(choices=[('text', 'text'), ('number', 'number'), ('select', 'select')], default='text', max_length=20)),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg_app.assistant')),
            ],
        ),
        migrations.CreateModel(
            name='LanguageAssistant',
            fields=[
                ('assistant_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rpg_app.assistant')),
            ],
            bases=('rpg_app.assistant',),
        ),
        migrations.CreateModel(
            name='InputOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=255)),
                ('assistant_input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg_app.assistantinput')),
            ],
        ),
    ]
