# Generated by Django 4.1.7 on 2023-02-24 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg_app', '0002_assistantinput_select_options_delete_inputoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='label',
            field=models.CharField(default='Random Roll Table', max_length=255),
            preserve_default=False,
        ),
    ]
