# Generated by Django 4.1.7 on 2023-02-24 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rpg_app', '0003_assistant_label'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LanguageAssistant',
        ),
        migrations.CreateModel(
            name='LanguageAssistant',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('rpg_app.assistant',),
        ),
    ]
