# Generated by Django 4.1.7 on 2023-02-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg_app', '0004_delete_languageassistant_languageassistant'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='assistant_type',
            field=models.CharField(choices=[('language', 'language'), ('image', 'image')], default='language', max_length=255),
            preserve_default=False,
        ),
    ]
